services:
  - type: web
    name: product-price-tracker-api
    env: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application --timeout 1800
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
