# Generated by Django 6.1.1 on 2026-09-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_product_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
